### ISSUE TITLE
Consider refactoring this lines to work without !important

### ISSUE THREAD

**Issue by dimshik100** [MSanbira/Taskboard#8]
https://github.com/MSanbira/Taskboard/blob/133d0ad667a47ee01212d8db7546863b2f4add39/css/main.css#L20

https://github.com/MSanbira/Taskboard/blob/133d0ad667a47ee01212d8db7546863b2f4add39/css/main.css#L24

**Comment by MSanbira** [comment]
Because Bootstrap contains the "show" class with !important then my decision was to write in the main css the "show" and "show-flex" in the same way for working in the same design system and control the attributes of the classes.
